### ISSUE TITLE
Contact Page Form Validation (CLIENT SIDE)

### ISSUE THREAD

**Issue by DanielWGross** [DanielWGross/cardinal_recording#16]
#### Description:
The contact form should be validated to ensure only clean data is being sent to the database and to the client e-mail address. The form should check for validation when the user attempts to submit and also after input is entered incorrectly and they have clicked off the box.

#### Tasks:
- [ ] Name field should validate that it is not empty & no HTML
- [ ] Email field should validate that it is not empty and also meets current standard. Unsure if this should be [RFC 2822](https://tools.ietf.org/html/rfc2822#section-3.4.1) or something else.
- [ ] Subject field should validate that it is not empty & no HTML.
- [ ] Message field should validate it is not empty & no HTML.
- [ ] JS validation should take place in contact.js file
- [ ] Any HTML validation should take place in the contact.handlebars file
- [ ] No basic alerts should be used. Consider modal or possibly [BootStrap style alerts](https://getbootstrap.com/docs/4.1/components/alerts/)
