### ISSUE TITLE
Contact Page Form Validation (SERVER SIDE)

### ISSUE THREAD

**Issue by DanielWGross** [DanielWGross/cardinal_recording#17]
#### Description:
After the contact form data has passed client side validation it should be validated and sanitized before being pushed into the database and onto the user e-mail. If there are any issues with the data the user should be notified and new information will need to be submitted again on the form.

#### Tasks:
- [ ] Name field should validate that it is not empty & no HTML
- [ ] Email field should validate that it is not empty and also meets current standard. Unsure if this should be [RFC 2822](https://tools.ietf.org/html/rfc2822#section-3.4.1) or something else.
- [ ] Subject field should validate that it is not empty & no HTML.
- [ ] Message field should validate it is not empty & no HTML.
- [ ] No basic alerts should be used. Consider modal or possibly [BootStrap style alerts](https://getbootstrap.com/docs/4.1/components/alerts/)
